import { ReactNode } from 'react';
import Link from 'next/link';
import { WalletButton } from '../solana/solana-provider';
import { Center, Box, Heading } from "@chakra-ui/react"
import { MovieList } from '../MovieList';
import { Form } from '../Form';
import { ChakraProvider } from "@chakra-ui/react";

export function AppLayout() {
  return (
    <ChakraProvider>
      <div style={{ display: 'flex', flexDirection: 'column', height: '100%' }}>
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            padding: '6px 12px',
          }}
        >
          <div>
            <Link href="/">
              <img src="/solanaLogo.png" width={200} alt="Logo" />
            </Link>
          </div>
          <div><h2>Movie Reviews</h2></div>
          <div>
            <WalletButton />
          </div>
        </div>
        <div style={{ flexGrow: 1, padding: '6px' }}>{<Home />}</div>
        <footer
          style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            padding: '6px 10px',
          }}
        >
          <aside>
            <p>
              Generated by{' '}
              <a
                href="https://github.com/solana-developers/create-solana-dapp"
                target="_blank"
                rel="noopener noreferrer"
              >
                create-solana-dapp
              </a>
            </p>
          </aside>
        </footer>
      </div>
    </ChakraProvider>
  );
}


const Home = () => {
  return (
    <Center>
      <Box >
        <Heading as="h1" size="l" color="white" ml={4} mt={8}>
          Add a review
        </Heading>
        <Form />
        <Heading as="h1" size="l" color="white" ml={4} mt={8}>
          Existing Reviews
        </Heading>
        <MovieList />
      </Box>
    </Center>
  )
}